apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: rabbit
  name: rabbitmq
spec:
  replicas: 1
  serviceName: rabbitmq
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.6.6-management-alpine
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "gutsandgun"
        - name: RABBITMQ_DEFAULT_PASS
          value: "gutsandgun"
        #- name: RABBITMQ_ERLANG_COOKIE
        #  value: "1WqgH8N2v1qDBDZDbNy8Bg9IkPWLEpu79m6q+0t36lQ="
        command:
        - bash
        - "-c"
        - |
          set -ex
          [[ $HOSTNAME =~ -([0-9]+)$ ]] || exit 1
          ordinal=${BASH_REMATCH[1]}
          mkdir -p /rabbitmq-vol
          mkdir -p /rabbitmq-vol/$ordinal
          mkdir -p /rabbitmq-vol/$ordinal/rabbitmq
          
          cp -r /rabbitmq-vol/.erlang.cookie /rabbitmq-vol/$ordinal/rabbitmq/
          until rabbitmqctl node_health_check; do sleep 1; done;
          sed -i 's@/var/lib/rabbitmq@/rabbitmq-vol/$ordinal/rabbitmq@g' /etc/rabbitmq/rabbitmq-env.conf
        volumeMounts:
        - mountPath: /rabbitmq-vol
          name: rabbitmq-data
      volumes:
      - name: rabbitmq-data # same as volumemouts name
        hostPath:
          path: /home/worker/k8s/rabbitmq