apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: rabbit
  name: rabbitmq
spec:
  replicas: 3
  serviceName: rabbitmq
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "gutsandgun"
        - name: RABBITMQ_DEFAULT_PASS
          value: "gutsandgun"
        #- name: RABBITMQ_ERLANG_COOKIE
        #  value: "1WqgH8N2v1qDBDZDbNy8Bg9IkPWLEpu79m6q+0t36lQ="
        command:
        - bash
        - "-c"
        - |
          set -ex
          [[ $HOSTNAME =~ -([0-9]+)$ ]] || exit 1
          ordinal=${BASH_REMATCH[1]}
          mkdir -p /rabbitmq-vol
          mkdir -p /rabbitmq-vol/$ordinal
          ln -s /rabbitmq-vol/$ordinal /var/lib/rabbitmq
          rabbitmqctl cluster_status
          if [[ $ordinal -eq 0 ]]; then
            rabbitmqctl set_policy ha-all "^ha\." '{"ha-mode":"all"}'
          else
            rabbitmqctl join_cluster rabbit@rabbitmq-0
            rabbitmqctl set_policy ha-all "^ha\." '{"ha-mode":"all"}'
          fi
        volumeMounts:
        - mountPath: /rabbitmq-vol
          name: rabbitmq-data
      volumes:
      - name: rabbitmq-data # same as volumemouts name
        hostPath:
          path: /home/worker/k8s/rabbitmq