apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: rabbit
  name: rabbitmq
spec:
  replicas: 3
  serviceName: rabbitmq
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      initContainers:
      - name: init-rabbitmq
        image: rabbitmq:3-management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "gutsandgun"
        - name: RABBITMQ_DEFAULT_PASS
          value: "gutsandgun"
        #- name: RABBITMQ_ERLANG_COOKIE
        #  value: "1WqgH8N2v1qDBDZDbNy8Bg9IkPWLEpu79m6q+0t36lQ="
        command:
        - bash
        - "-c"
        - |
          set -ex
          [[ $HOSTNAME =~ -([0-9]+)$ ]] || exit 1
          ordinal=${BASH_REMATCH[1]}
          mkdir -p /rabbitmq-vol
          mkdir -p /rabbitmq-vol/$ordinal
          mkdir -p /rabbitmq-vol/$ordinal/rabbitmq
          ln -s  /rabbitmq-vol/$ordinal/rabbitmq /var/lib/rabbitmq
          cp -r /rabbitmq-vol/.erlang_cookie /var/lib/rabbitmq/
          if [[ ! $ordinal -eq 0 ]]; then
            rabbitmqctl join_cluster rabbit@rabbit0
            rabbitmqctl change_cluster_node_type ram
          else
            rabbitmqctl change_cluster_node_type disk
          fi
        volumeMounts:
        - mountPath: /rabbitmq-vol
          name: rabbitmq-data
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "gutsandgun"
        - name: RABBITMQ_DEFAULT_PASS
          value: "gutsandgun"
        #- name: RABBITMQ_ERLANG_COOKIE
        #  value: "1WqgH8N2v1qDBDZDbNy8Bg9IkPWLEpu79m6q+0t36lQ="
        volumeMounts:
        - mountPath: /rabbitmq-vol
          name: rabbitmq-data
      volumes:
      - name: rabbitmq-data # same as volumemouts name
        hostPath:
          path: /home/worker/k8s/rabbitmq