apiVersion: v1
kind: Service
metadata:
  name: read-service
spec:
  type: ExternalName
  externalName: read-statefulset-0.only-read-service.db.svc.cluster.local
---
# Client service for connecting to any MySQL instance for reads.
# For writes, you must instead connect to the primary: mysql-0.mysql.
apiVersion: v1
kind: Service
metadata:
  name: only-read-service
  labels:
    app: read
    readonly: "true"
spec:
  ports:
  - name: read-statefulset
    port: 3306
  selector:
    app: read
   