apiVersion: v1
kind: ConfigMap
metadata:
  name: master.cnf
data:
  master.cnf: |
    [mariadb]
    log-bin
    binlog_format = ROW
    default-time-zone='+9:00'
    
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: slave.cnf
data:
  slave.cnf: |
    [mariadb]
    super-read-only
    default-time-zone='+9:00'