apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: read-statefulset
  labels:
    app: read
spec:
  serviceName: read-service
  replicas: 1
  selector:
    matchLabels:
      app: read
  template:
    metadata:
      labels:
        app: read
    spec:
      containers:
      - name: read
        image: mariadb
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: gutsandgun
        volumeMounts:
        - name: read-pvc
          mountPath: /var/lib/mysql
        - name: config
          mountPath: /etc/mysql/conf.d
      volumes:
       - name: read-pvc # same as volumemouts name
         nfs:
           server: 172.30.1.100
           path: /k8s/db_set/read
       - name: config
         configMap:
           name: master.cnf