apiVersion: apps/v1
kind: Deployment
metadata:
  name: readdb-statefulset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: readdb
  template:
    metadata:
      labels:
        app: readdb
    spec:
      containers:
      - name: readdb
        image: mariadb
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: gutsandgun
        volumeMounts:
        - name: readdb-pvc
          mountPath: /var/lib/mysql
      volumes:
       - name: readdb-pvc # same as volumemouts name
         nfs:
           server: 172.30.1.100
           path: /k8s/db_set/readdb