apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: readdb-statefulset
  labels:
    app: readdb
spec:
  serviceName: readdb-service
  replicas: 1
  selector:
    matchLabels:
      app: readdb
  template:
    metadata:
      labels:
        app: readdb
    spec:
      containers:
      - name: readdb
        image: mariadb
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: gutsandgun
        volumeMounts:
        - name: readdb-pvc
          mountPath: /var/lib/mysql
        - name: config
          mountPath: /etc/mysql/conf.d
      volumes:
       - name: readdb-pvc # same as volumemouts name
         nfs:
           server: 172.30.1.100
           path: /k8s/db_set/readdb
       - name: config
         configMap:
           name: db_config