apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user
spec:
  ports:
  - name: user-statefulset
    port: 3306
  selector:
    app: user
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127
  