apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user
spec:
  ports:
  - name: user-statefulset
    port: 80
    targetPort: 3306
  selector:
    app: user
---
apiVersion: v1
kind: Endpoints
metadata:
  # 여기서의 이름은 서비스의 이름과 일치해야 한다.
  name: user-service
subsets:
  - addresses:
      - ip: 192.168.25.241
    ports:
      - port: 80