apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-statefulset
  labels:
    app: user
spec:
  serviceName: user-service
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: mariadb
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: gutsandgun
        volumeMounts:
        - name: user-pvc
          mountPath: /var/lib/mysql
        - name: config
          mountPath: /etc/mysql/conf.d
      volumes:
       - name: user-pvc # same as volumemouts name
         nfs:
           server: 172.30.1.100
           path: /k8s/db_set/user
       - name: config
         configMap:
           name: master.cnf