apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  namespace: metallb-system
  name: metallb-config
spec:
  addresses:
  - 192.168.24.240-192.168.24.250
  - 192.168.25.241-192.168.24.250

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  namespace: metallb-system
  name: metallb-network-l2
spec:
  ipAddressPools:
  - metallb-config