apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: elastic-sink
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-connect-cluster3
spec:
  class: io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
  config:
    tasks.max: 1
    topics: fluentd-container-logging
    topic.index.map: fluentd:fluentd_index
    connection.url: kafka-cluster-kafka-brokers:9092
    type.name: log
    key.ignore: true
    schema.ignore: true