apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: elastic-sink
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-connect-cluster3
spec:
  config:
    connector.class: io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
    tasks.max: 1
    topics: fluentd-container-logging
    topic.index.map: fluentd:fluentd_index
    connection.url: http://elasticsearch-svc:9200
    type.name: log
    key.ignore: true
    schema.ignore: true