apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: elasticsearch-sink
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-connect-cluster3
spec:
  class: io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
  config:
    tasks.max: 1
    topics: fluentd-container-logging
    topic.index.map: fluentd-container-logging:fluentd_index
    connection.url: http://elasticsearch-svc.monitoring.svc.cluster.local:9200
    type.name: log
    key.ignore: true
    schema.ignore: true
    key.converter: io.confluent.connect.avro.AvroConverter
    key.converter.schema.registry.url: http://schema-registry.kafka.svc.cluster.local:8081
    value.converter: io.confluent.connect.avro.AvroConverter
    value.converter.schema.registry.url: http://schema-registry.kafka.svc.cluster.local:8081
    
    transforms: unwrap, route
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: false
    transforms.route.type: org.apache.kafka.connect.transforms.RegexRouter
    transforms.route.regex: "([^.]+)\\.([^.]+)\\.([^.]+)"
    transforms.route.replacement: $3